version: "3.9"
services:
    web:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/app
              - node_modules:/app/node_modules
        environment:
            - NODE_ENV=development
        command: npm run dev
        env_file:
            - .env

volumes:
    node_modules:
